spring:
  application:
    name: book-store
server:
  port: 8889
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka
  instance:
    preferIpAddress: true

jaeger.tracer:
  host: localhost
  port: 6831